# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./meta_qpn_qt.h \
    ../../Meta_QPN/Meta_QPN/i_qpn_descriptor.h \
    ../../Meta_QPN/Meta_QPN/qpn_additive_synergy.h \
    ../../Meta_QPN/Meta_QPN/qpn_context_specific.h \
    ../../Meta_QPN/Meta_QPN/qpn_descriptor_directed.h \
    ../../Meta_QPN/Meta_QPN/qpn_descriptor_undirected.h \
    ../../Meta_QPN/Meta_QPN/qpn_influence.h \
    ../../Meta_QPN/Meta_QPN/qpn_nm_influence.h \
    ../../Meta_QPN/Meta_QPN/qpn_product_synergy.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge_additive_synergy.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge_context_specific.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge_influence.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge_nm_influence.h \
    ../../Meta_QPN/Meta_QPN/qpn_edge_product_synergy.h \
    ../../Meta_QPN/Meta_QPN/meta_qpn_controller.h \
    ../../Meta_QPN/Meta_QPN/qpn_sign.h \
    ../../Meta_QPN/Meta_QPN/suffix_tree.h \
    ../../Meta_QPN/Meta_QPN/qpn_node.h
SOURCES += ./main.cpp \
    ./meta_qpn_qt.cpp \
    ../../Meta_QPN/Meta_QPN/qpn_edge.cpp \
    ../../Meta_QPN/Meta_QPN/qpn_edge_additive_synergy.cpp \
    ../../Meta_QPN/Meta_QPN/qpn_edge_influence.cpp \
    ../../Meta_QPN/Meta_QPN/qpn_sign.cpp \
    ../../Meta_QPN/Meta_QPN/meta_qpn_controller.cpp
FORMS += ./meta_qpn_qt.ui
RESOURCES += meta_qpn_qt.qrc
